title: Testing
default_theme: dark
cards:
  - id: list
    elements:
      - link: www.google.com
        text: testing google
      - text: just text
      - link: justlink.com
  - id: list
    rowSpan: 2
    colSpan: 1
  - id: spacer
  - id: error
    text: 'Error!'
